<?php
/**
 * CompanyConfirmationStatusEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cargomart API v2
 *
 * REST-Full API для логистической биржи cargomart.ru
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@cargomart.ru
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MagDv\Cargomart\Dto;
use \MagDv\Cargomart\ObjectSerializer;

/**
 * CompanyConfirmationStatusEnum Class Doc Comment
 *
 * @category Class
 * @description Текущий статус валидации/шаг/экран
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompanyConfirmationStatusEnum
{
    /**
     * Possible values of this enum
     */
    public const ROLE_SELECT = 'ROLE_SELECT';

    public const COMPANY_SET = 'COMPANY_SET';

    public const KONTUR_WAIT = 'KONTUR_WAIT';

    public const COMPANY_NOT_EXISTS = 'COMPANY_NOT_EXISTS';

    public const COMPANY_CONFIRM = 'COMPANY_CONFIRM';

    public const COMPANY_EXISTS = 'COMPANY_EXISTS';

    public const COMPANY_PROFILE = 'COMPANY_PROFILE';

    public const COMPANY_WAIT = 'COMPANY_WAIT';

    public const DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD';

    public const DOCUMENT_FOREIGN_UPLOAD = 'DOCUMENT_FOREIGN_UPLOAD';

    public const DOCUMENT_WAIT = 'DOCUMENT_WAIT';

    public const DOCUMENT_SUCCESS = 'DOCUMENT_SUCCESS';

    public const DOCUMENT_REJECT = 'DOCUMENT_REJECT';

    public const BLOCKED_BY_INN = 'BLOCKED_BY_INN';

    public const BLOCKED_BY_DOCS = 'BLOCKED_BY_DOCS';

    public const INCOME_REQUEST_WAIT = 'INCOME_REQUEST_WAIT';

    public const COMPANY_PROFILE_FINISHED = 'COMPANY_PROFILE_FINISHED';

    public const CONTRACT_CONCLUSION = 'CONTRACT_CONCLUSION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ROLE_SELECT,
            self::COMPANY_SET,
            self::KONTUR_WAIT,
            self::COMPANY_NOT_EXISTS,
            self::COMPANY_CONFIRM,
            self::COMPANY_EXISTS,
            self::COMPANY_PROFILE,
            self::COMPANY_WAIT,
            self::DOCUMENT_UPLOAD,
            self::DOCUMENT_FOREIGN_UPLOAD,
            self::DOCUMENT_WAIT,
            self::DOCUMENT_SUCCESS,
            self::DOCUMENT_REJECT,
            self::BLOCKED_BY_INN,
            self::BLOCKED_BY_DOCS,
            self::INCOME_REQUEST_WAIT,
            self::COMPANY_PROFILE_FINISHED,
            self::CONTRACT_CONCLUSION
        ];
    }
}


