<?php
/**
 * OrderPatchType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cargomart API v2
 *
 * REST-Full API для логистической биржи cargomart.ru
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@cargomart.ru
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MagDv\Cargomart\Dto;
use \MagDv\Cargomart\ObjectSerializer;

/**
 * OrderPatchType Class Doc Comment
 *
 * @category Class
 * @description Тип запроса на изменение заявки
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderPatchType
{
    /**
     * Possible values of this enum
     */
    public const EXPEDITOR_CHANGES = 'expeditor-changes';

    public const TRUCK_DRIVER_CHANGES = 'truck-driver-changes';

    public const CUSTOMER_CHANGES = 'customer-changes';

    public const REFUSE_REVERT = 'refuse-revert';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXPEDITOR_CHANGES,
            self::TRUCK_DRIVER_CHANGES,
            self::CUSTOMER_CHANGES,
            self::REFUSE_REVERT
        ];
    }
}


