<?php
/**
 * ProposalCarrierPaymentTypeEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cargomart API v2
 *
 * REST-Full API для логистической биржи cargomart.ru
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@cargomart.ru
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MagDv\Cargomart\Dto;
use \MagDv\Cargomart\ObjectSerializer;

/**
 * ProposalCarrierPaymentTypeEnum Class Doc Comment
 *
 * @category Class
 * @description Тип оплаты
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProposalCarrierPaymentTypeEnum
{
    /**
     * Possible values of this enum
     */
    public const PAYMENT_BY_DOC_COPIES = 'paymentByDocCopies';

    public const FAST_PAYMENT_BY_DOC_COPIES = 'fastPaymentByDocCopies';

    public const PAYMENT_BY_DOC_ORIGINAL = 'paymentByDocOriginal';

    public const FAST_PAYMENT_BY_DOC_ORIGINAL = 'fastPaymentByDocOriginal';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PAYMENT_BY_DOC_COPIES,
            self::FAST_PAYMENT_BY_DOC_COPIES,
            self::PAYMENT_BY_DOC_ORIGINAL,
            self::FAST_PAYMENT_BY_DOC_ORIGINAL
        ];
    }
}


