<?php
/**
 * TruckOwnershipType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cargomart API v2
 *
 * REST-Full API для логистической биржи cargomart.ru
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@cargomart.ru
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MagDv\Cargomart\Dto;
use \MagDv\Cargomart\ObjectSerializer;

/**
 * TruckOwnershipType Class Doc Comment
 *
 * @category Class
 * @description Тип владения (owned - Собственность, leasing - Лизинг, rent - Аренда, joint_property_spouses - Совместная собственность супругов, free_use - Безвозмездное пользование)
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TruckOwnershipType
{
    /**
     * Possible values of this enum
     */
    public const OWNED = 'owned';

    public const LEASING = 'leasing';

    public const RENT = 'rent';

    public const JOINT_PROPERTY_SPOUSES = 'joint_property_spouses';

    public const FREE_USE = 'free_use';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OWNED,
            self::LEASING,
            self::RENT,
            self::JOINT_PROPERTY_SPOUSES,
            self::FREE_USE
        ];
    }
}


