<?php
/**
 * OrderStatusEnumTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cargomart API v2
 *
 * REST-Full API для логистической биржи cargomart.ru
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@cargomart.ru
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MagDv\Cargomart\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderStatusEnumTest Class Doc Comment
 *
 * @category    Class
 * @description Статус заказа: 0-template, 1-temp, 2-draft, 3-published, 4-playing, 5-processing, 6-performing, 7-finished, 8-archived, 9-deleted, 21-moderation, 22-moderation_reject, 23-booking_moderation_reject, 250-not_approved, 240-approved, 230-proxy_uploaded, 100-no_bids, 140-other_refuse, 110-carrier_refuse, 120-consignor_refuse, 130_canceled, 90-imported
 * @package     MagDv\Cargomart
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrderStatusEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderStatusEnum"
     */
    public function testOrderStatusEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
