<?php
/**
 * ExpeditorOfferApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cargomart API v2
 *
 * REST-Full API для логистической биржи cargomart.ru
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@cargomart.ru
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MagDv\Cargomart\Test\Api;

use \MagDv\Cargomart\Configuration;
use \MagDv\Cargomart\ApiException;
use \MagDv\Cargomart\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExpeditorOfferApiTest Class Doc Comment
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExpeditorOfferApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2ExpeditorProposalIdExpeditorOfferGet
     *
     * Список предложений от перевозчиков для экспедитора..
     *
     */
    public function testApiV2ExpeditorProposalIdExpeditorOfferGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2OrderOrderIdExpeditorOfferGet
     *
     * Список предложений от перевозчиков для отправителя..
     *
     */
    public function testApiV2OrderOrderIdExpeditorOfferGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2OrderOrderIdExpeditorOfferPost
     *
     * Создание или замена предложения перевозчика по заказу.
     *
     */
    public function testApiV2OrderOrderIdExpeditorOfferPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2OrderOrderIdNegotiatePost
     *
     * Изменение заказчиком условий заказа, чтобы ближе соответствовать поступившим предложениям от перевозчиков.
     *
     */
    public function testApiV2OrderOrderIdNegotiatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
