<?php
/**
 * ExpeditorTaskApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cargomart API v2
 *
 * REST-Full API для логистической биржи cargomart.ru
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@cargomart.ru
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MagDv\Cargomart\Test\Api;

use \MagDv\Cargomart\Configuration;
use \MagDv\Cargomart\ApiException;
use \MagDv\Cargomart\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExpeditorTaskApiTest Class Doc Comment
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExpeditorTaskApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for freezeExpeditorTask
     *
     * Откладывание задачи.
     *
     */
    public function testFreezeExpeditorTask()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExpeditorTask
     *
     * Получение информации о задаче.
     *
     */
    public function testGetExpeditorTask()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExpeditorTaskList
     *
     * Получение списка задач.
     *
     */
    public function testGetExpeditorTaskList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for selfAssignExpeditorTask
     *
     * Прикрепление задачи к себе.
     *
     */
    public function testSelfAssignExpeditorTask()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendExpeditorTaskResolution
     *
     * Отправка резолюции.
     *
     */
    public function testSendExpeditorTaskResolution()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unassignExpeditorTask
     *
     * Открепление задачи от себя.
     *
     */
    public function testUnassignExpeditorTask()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
