<?php
/**
 * SimpleDocumentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cargomart API v2
 *
 * REST-Full API для логистической биржи cargomart.ru
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@cargomart.ru
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MagDv\Cargomart\Test\Api;

use \MagDv\Cargomart\Configuration;
use \MagDv\Cargomart\ApiException;
use \MagDv\Cargomart\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SimpleDocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MagDv\Cargomart
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SimpleDocumentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2SimpleDocumentPreviewGet
     *
     * Превью PDF-файла для титула ЭДО-документа перед подписанием им..
     *
     */
    public function testApiV2SimpleDocumentPreviewGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2SimpleDocumentRootIdGet
     *
     * Детали по подписанному документу заказа..
     *
     */
    public function testApiV2SimpleDocumentRootIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
